# Generated by Django 4.1.1 on 2022-09-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=50, verbose_name='Двигатель')),
            ],
            options={
                'verbose_name': 'Двигатель',
                'verbose_name_plural': 'Двигатели',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Марка Авто', 'verbose_name_plural': 'Марки авто'},
        ),
    ]
