# Generated by Django 4.1.1 on 2022-09-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_engine_alter_car_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand_image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение авто'),
        ),
    ]
